### ISSUE TITLE
Envify Generator fails due to dependency issue with crypto

### ISSUE THREAD

**Issue by sharfaz** [frencojobs/envify#12] opened 2021-03-16 22:26 UTC
Hi 

I am getting following error when I try to install this package.

`Because every version of envify_generator depends on analyzer ^0.40.4 which depends on crypto ^2.0.0, every version of envify_generator requires crypto ^2.0.0.
And because google_fonts 2.0.0 depends on crypto ^3.0.0 and no versions of google_fonts match >2.0.0 <3.0.0, envify_generator is incompatible with google_fonts ^2.0.0.
So, because salary_extras depends on both google_fonts ^2.0.0 and envify_generator 1.1.0, version solving failed.
pub get failed (1; So, because salary_extras depends on both google_fonts ^2.0.0 and envify_generator 1.1.0, version solving failed.)`

**Comment by frencojobs** [comment] 2021-03-17 01:46
May I know your dart environment version and flutter version, plus which versions of envify_generator and google_fonts are you using?

**Comment by sharfaz** [comment] 2021-03-17 08:18
I am running on Mac with latest flutter and dart versions as below

Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git \
Framework • revision 8962f6dc68 (5 days ago) • 2021-03-11 13:22:20 -0800 \
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1

I am using latest **envy_generator 1.1.0** and I am using google fonts **google_fonts: ^2.0.0**

**Comment by frencojobs** [comment] 2021-03-22 05:43
Hey, Frenco here.

Thanks for the details. And sorry for the delay. I'm having a difficult time here due to situations regarding my country with internet blackouts. I won't be able to check the issue for now. But I think it could be solved by using lower versions of the packages.

Sorry for the inconvenience. I hope you could understand. Thanks.

**Comment by nstrelow** [comment] 2021-04-08 14:02
I wish you all the best. Stay safe 🙏

**Comment by frencojobs** [comment] 2021-06-14 16:14
Hey :wave:. I took a look at this issue again and found out that this only happens because of not-fully-migrated `envify_generator` version 1.1.0.

Now that envify is fully migrated to null-safety and with `envify_generator` at v2.0.0, this issue should not happen. In fact, I've checked myself, with all the latest versions (at the time of this writing) of both `google_fonts`, `envify_generator`, and `envify`, I can confirm everything is working as expected.

So, I'm closing the issue. Feel free to reopen it in case the issue is not fully resolved or something. Thanks a lot for taking the time to file the issue. I really appreciate that.

**Closed by frencojobs** 2021-06-14 16:14 UTC
Labels: bug
